---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-9.0}-russian-ca-certificates"
    hostname: russian-ca-certificates
    # Systemd is absent in rockylinux 9.1 docker image.
    # https://github.com/rocky-linux/sig-cloud-instance-images/issues/39
    image: "${NAMESPACE:-library}/${IMAGE:-rockylinux}:${TAG:-9.0}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint